Add new  grpc
dubbogo/tools pull request #21
Opened 2021-11-17 09:58 UTC by jasondeng1997

Add new  grpc

2021-11-17 10:46 UTC, cjphaha approved these changes

2021-11-17 10:46 UTC, cjphaha commented
LGTM👍

2021-11-17 10:48 UTC, cjphaha commented
这个最好在根目录的 readme 里面加一个说明

2021-11-17 10:59 UTC, zhaoyunxing92 approved these changes

2021-11-17 11:16 UTC, AlexStocks commented on cmd/grpc/client.go
> +func clientInit() {
initClient

2021-11-17 11:19 UTC, AlexStocks commented on cmd/grpc/client.go
> +	} else {
这段 if-else 代码贼难看

```go
    if protocolConf == nil {
		logger.Error("protocol_conf default use dubbo config")
                return
	} 
```

然后把 else 去掉

2021-11-17 11:20 UTC, AlexStocks commented on cmd/grpc/client_test.go
> +	"context"
split it

2021-11-17 11:21 UTC, AlexStocks commented on cmd/grpc/grpc_invoker_test.go
> +import (
split it

2021-11-17 15:23 UTC, jasondeng1997 commented
都改了，你们再看看吧

2021-11-18 05:09 UTC, AlexStocks commented on cmd/grpc/client.go
> +var clientConf *ClientConfig
像 import 一样，如果有连续多个 var，写成 var ()

var (
  clientConf *ClientConfig
  clientConfInitOnce sync.Once
)

2021-11-18 05:11 UTC, AlexStocks commented on cmd/grpc/config.go
> +	return ServerConfig{}
这封装没啥意义，我觉得

2021-11-18 05:11 UTC, AlexStocks commented on cmd/grpc/config.go
> +	return ClientConfig{}
这封装没啥意义，我觉得

2021-11-18 05:31 UTC, LaurenceLiZhixin requested changes
只需要拿过来protoc-gen-go-dubbo3grpc

2021-11-18 05:35 UTC, closed without merging